#!/bin/sh
ssh ubuntu@99.79.88.73 <<EOF     
  cd /home/ubuntu
  cd cd /var/www/html/dashabit_backend/backend/
  git pull https://github.com/ANKITVARSHNEY19/demo-repo
  bundle install && rails db:migrate
EOF